### ISSUE TITLE
How to load ionic2 app via localhost using cordova httpd plugin?

### ISSUE THREAD

**Issue by nampdn** [driftyco/ionic-native#1000]
Hi, 
I'm trying to load my app via `http://` protocol instead of `file:///` for production. Because my ionic app have to implement [a external media player library](https://github.com/google/shaka-player/issues/543) that is not support to make direct ajax request through `file:///` protocol.

I checked that there is [a plugin](http://ionicframework.com/docs/v2/native/httpd/) for this. Please help me to start the server and load the app via `http://`.

I have tried the example and implement this code to my `app.component.ts`:

        this.platform.ready().then(() => {
            // Okay, so the platform is ready and our plugins are available.
            // Here you can do any higher level native things you might need.
            StatusBar.styleDefault();
            Splashscreen.hide();
            let options: HttpdOptions = {
                www_root: './', // relative path to app's www directory, not sure how to set default value to www dir
                port: 8080,
                localhost_only: true
            };

            Httpd.startServer(options).subscribe((data) => {
                console.log('Server is live', data);
                document.location.href=data; //This line cause open the external browser instead of load the app in cordova webview
            });
        });

**Comment by ihadeed** [comment]
Closing this issue since this is not a question for Ionic Native. This would be something to discuss in the forums.

Here's what I think:

I think this can work by creating a second app _(doesn't have to be a full ionic 2 app, it can be a small single page that only takes care of the streaming)_. Place that app in a directory other than your app's root directory. Then start an _Httpd_ server in that directory and open it using `InAppBrowser` plugin. You can then communicate with the page using events or by manipulating the URL (hash urls). 

The second option is to modify the Cordova platform, use a native library to host your app over HTTP, then open it using WebView instead of the `file:///` url. 

---

If you need further help, please open a thread at the forums: https://forum.ionicframework.com/

Good luck!
