### ISSUE TITLE
bug: ionic-native: InAppBrowser object reference lost

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#1014]
_From @othon2000 on January 27, 2017 16:21_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>## not sure if it also affects iOS, couldn't verify yet

If you have an instance of InAppBrowser, say, with target=_blank, and then you create a new instance with target=_system, your original InAppBrowser reference gets lost, and the events assigned to it stop working.

```javascript
  let blankBrowser = new InAppBrowser('https://someurl.com', '_blank', 'location=no,zoom=no,hidden=no');
  blankBrowser.on('loadstart').subscribe(
    event => {
      //some behavior
    }
  );
  let systemBrowser = new InAppBrowser('https://anotherurl.com', '_system', 'location=no,zoom=no,hidden=no');
  //bang! the events assigned to blankBrowser go away, and I cannot do anything with the reference
```
</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#10210_

**Comment by ihadeed** [comment]
This issue is caused by the way the plugin is built. We have no control over it at Ionic Native. 

I suggest you open an issue with them: https://issues.apache.org/jira/issues/?jql=project%20%3D%20CB%20AND%20status%20in%20%28Open%2C%20%22In%20Progress%22%2C%20Reopened%29%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20%22Plugin%20InAppBrowser%22%20ORDER%20BY%20priority%20DESC%2C%20summary%20ASC%2C%20updatedDate%20DESC

**Comment by othon2000** [comment]
@ihadeed and @jgw96 thank you, just opened the issue with the Cordova folks: https://issues.apache.org/jira/browse/CB-12407
appreciate if you could vote it

**Comment by adirel** [comment]
did you workout a solution ?

**Comment by othon2000** [comment]
Not really. I moved to a solution using iframe and Window.postMessage()

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
