### ISSUE TITLE
Documentations for developer falls severly short

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic-native#103]
The documentation for developer misses important components in how-to-start and how to test.
The documentation doesn't match the files I see in node_modules/ionic-native... how are those generated ? 

There are many cordova plugins written by individuals that I want to use like the ones in Ionic-native. Unfortunately, the documentation here is not sufficient.

**Comment by ihadeed** [comment]
Hey @panuganti ,

I'm sorry that you are having a hard time following up with the current version of the documentation. I understand the frustration you are going through. 

The developers and contributors of Ionic Native are constantly working on improving the documentation. There will certainly be a more thorough documentation available in the near future.

Here's a quick-fix, you are able to see the latest version of the docs by going to the Ionic Framework Staging site. Be aware, that some plugins that are documented there are still not available in the stable version provided via the NPM package. Double check that you have the plugin definition available before trying to use it.

http://ionic-site-staging.herokuapp.com/docs/v2/native/

**Comment by panuganti** [comment]
Thanks for the response. Those plugins that you already have are great.
I was looking to add the WebIntent plugin. While your documentation here describes how to write a corresponding typescript file to be added to this repository..but, what I miss is how it goes from there to other native plugins like the set you have pointed to.
At least, when I look at the files in node_modules/ionic-native, they are very different.

Ionic-v2 is awesome and the approach you guys took with native is awesome too but, few minor enhancements (like a slack channel and better documentation for using plugins that are not yet part of ionic-native) would take it a long way.

Also, it;d be great if you guys can have a slack channel on ionic-worldwide.. your channel (esp. ionic-v2) has been so helpful with mike and regular folks from the community helping each other..If you see that channel, many are struggling with issues with Ionic native and services like Push... and a separate slack channel would help immensely.

**Comment by tlancina** [comment]
Hey @panuganti sorry you're having problems.  The reason the code that is distributed is so different from the source code is because it's being transpiled from TypeScript to ES5.  You can read more about some of the technologies involved here: http://ionicframework.com/docs/v2/resources/what-is/#typescript, as well as on the Ionic Forums: https://forum.ionicframework.com/. I believe Mike also added an #ionic-native channel to the Ionic Worldwide Slack group today.

Going to close this as I don't think there's any more actionable feedback for us, but let us know if you're still having issues, thanks!
