### ISSUE TITLE
Property 'type' does not exist on type 'typeof Network'. 

### ISSUE THREAD

**Issue by wundo** [driftyco/ionic-native#1092]
The documentation states that Network.type should be accessible, but it currently doesn't exists.

**Comment by ihadeed** [comment]
What version of Ionic Native are you using?

**Comment by wundo** [comment]
Not closed, I'm on 2.2.11

**Comment by ihadeed** [comment]
@wundo please update to `2.2.12` at least. 

The latest stable version is `2.7.0`.

**Comment by wundo** [comment]
Nevermind, my package.json was outdated, but:

```
npm info ionic-native version
2.7.0
```

And the issue still occurs

**Comment by ihadeed** [comment]
@wundo 

The property `type` is defined right here: https://github.com/driftyco/ionic-native/blob/master/src/plugins/network.ts#L59

In run-time Ionic Native will call `pluginRef` + property name to get you the value. So it will be getting the value from `navigator.connection.type`. That matches what they have in their docs here: https://github.com/apache/cordova-plugin-network-information#properties

I don't see where the problem is, I tested this not too long ago. Try the following:
```
npm rm --save ionic-native
npm i --save ionic-native@latest
```

**Comment by chenlitchian** [comment]
@wundo  the link u provided cant be found, I have this problem too.


            Property 'type' does not exist on type 'typeof Network'.

      L44:     if( Network.type === 'none') {
      L45:         let alert = this.alertCtrl.create({

**Comment by ihadeed** [comment]
@chenlitchian https://github.com/driftyco/ionic-native/blob/v2.x/src/plugins/network.ts#L59
