### ISSUE TITLE
google-analytics cannot be imported as a single plugin

### ISSUE THREAD

**Issue by dkarpik** [driftyco/ionic-native#1134]
Hi, 
It is impossible to import google-anlytics from ionic-native as a single plugin.

I am importing it as follows :
`import { GoogleAnalytics } from '@ionic-native/google-analytics';`

As a result, `GoogleAnalytics` is recognised by typescript as injectable object which does not have any static members, so it cannot be compiled when i am trying to use some of plugin methods.

Any workaround for this issue?

**Comment by ihadeed** [comment]
What version are you installing?

**Comment by dkarpik** [comment]
Sorry, i forgot to mention.

It is: `3.1.0-alpha.1`

**Comment by ihadeed** [comment]
Since v3.1.0 all plugins are injectable, there are no more static methods.

If you want to use v3 and stay with static methods for now, please install 3.0.x.

Here is how you use 3.1.0-alpha:

First, make sure you have `@ionic-native/core` and the plugins you need installed at version `3.1.0-alpha.3`. You can do that by running these commands:
```shell
npm i --save @ionic-native/core@alpha
npm i --save @ionic-native/google-analytics@alpha
```

Then import the plugin in your app's module:
```
import { GoogleAnalytics } from '@ionic-native/google-analytics';
@NgModule({
...
  providers: [ GoogleAnalytics ]
...
})
```

Finally, inject it in any component or service to use it:
```
constructor(private ga: GoogleAnalytics) { }

initGA(){ 
  this.ga.startTrackerWithId(....);
}

trackSomething() {
  this.ga.trackView(...)
}
```
