### ISSUE TITLE
New Release to satisfy ionic 2.0.0-beta.4 dependencies 

### ISSUE THREAD

**Issue by DavidWiesner** [driftyco/ionic-native#119]
Please release a new Version to satisfy the new dependencies of [ionic 2.0.0-beta.4](https://github.com/driftyco/ionic/releases/tag/v2.0.0-beta.4)

Ionic 2.0.0-beta.4 require rxjs 5.0.0-beta.2 but ionic-native require 5.0.0-beta.0 in last released version. There is already a [commit](https://github.com/driftyco/ionic-native/commit/139673e0102c5b60452f11f46f43ba66a1b331a7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) with this change but no release with this change.

regards,
David

**Comment by tlancina** [comment]
Just published a new release, let us know if you have issues, thanks!

**Comment by rob3c** [comment]
The rxjs dependency should probably be declared in `peerDependencies` instead of `dependencies` in _package.json_, since the idea is to interop with the rest of the ionic app rather than it being self-contained in the module. That would parallel angular2's `peerDependencies` rxjs declaration, which ionic itself transitively depends on via its `peerDependencies` declaration for angular2.

Also, since ionic-native only seems to use rxjs in a simple way for the `Observable` definition and the occasional `subscribe` call from my scan through the source - i.e. things that aren't likely to break in further beta releases - you could minimize the maintenance headache for this by setting a range just for the beta, like `>5.0.0-beta <5.0.0` or similar.
