### ISSUE TITLE
ionic-native vs @ionic-native/core?

### ISSUE THREAD

**Issue by tscislo-lingaro** [driftyco/ionic-native#1266]
Hello,
What is the difference between https://www.npmjs.com/package/ionic-native and https://www.npmjs.com/package/@ionic-native/core ?
I know that core is just core for ionic-native, but I'm more interested if those versions go hand in hand?

**Comment by ValentinKlinghammer** [comment]
No, they don't. `@ionic-native/core` is the current version (3.x) and let's you choose each individual module instead of including them all at once like the old version `ionic-native` (2.x) did. Since the naming is different, I assume the old npm package is kept (also for backwards compatibility).

For more details, see *"Usage"* in the [Docs](https://ionicframework.com/docs/v2/native/).
