### ISSUE TITLE
alert popup buttons are not working on native cordova google map.

### ISSUE THREAD

**Issue by narayansikarwar** [driftyco/ionic-native#1278]
When I click on OK button inside alert then map zoom is triggered and alert button is not clicking. So can you please tell how it's working with native map.

![capture](https://cloud.githubusercontent.com/assets/19340500/24402438/3ceb558c-13d6-11e7-8262-d4943a365c6c.PNG)

**Comment by ihadeed** [comment]
I think this is because the native map is handling all the click events, and the actual Alert component isn't receiving them. 

What I would do in this situation is use the `Dialogs` plugin to display a native Dialog instead of the Ionic Framework's Alert component.

I'm closing this issue since it's not an Ionic Native issue. I suggest seeking help in the Ionic Forums to see if anyone else has found a solution for this.
