### ISSUE TITLE
Please add the Cordova Screenshot plugin

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic-native#137]
Can I request you to please add the cordova screenshot plugin to Ionic 2 (with typescript)
https://github.com/gitawego/cordova-screenshot

Thanks.

**Comment by ihadeed** [comment]
Interesting plugin!

Will add soon.

**Comment by panuganti** [comment]
@ihadeed, I am attempting to give a shot to contributing to this repo by adding this plugin. If you can please guide me through this one, I'll be contributing to few/many more plugins and also more importantly to the documentation for developers.

I. I tried to send a pull request from my master branch using `git pull` but, got this error
``` 
remote: Permission to driftyco/ionic-native.git denied to panuganti.
fatal: unable to access 'https://github.com/driftyco/ionic-native.git/': The requested URL returned error: 403
``` 

Here is the list of steps I did: (the first part of the steps are missing in the documentation)
1. git clone https://github.com/driftyco/ionic-native.git
2. cd ionic-native and then npm install
`Ques: when I traverse to demo folder and do npm install, I run into errors. How do I run the demo ?`
3. Following the developer guide, I have written the corresponding .ts file. For this plugin, it requires a callback, which in-turn handles the err and succ. The developer guide assumes that there are succ and err callbacks in the function itself.

Since, I'm unable to do a push request, here's the code I've written (and the added export to index.ts etc..). 
Can you please guide me on the missing steps/mistakes that I'm doing and also, how do I test this ? 

```
import {Cordova, CordovaProperty, Plugin} from './plugin';
declare var window;
@Plugin({
  plugin: 'https://github.com/gitawego/cordova-screenshot.git',
  pluginRef: 'navigator.screenshot',
  repo: 'https://github.com/gitawego/cordova-screenshot.git'
})
export class Screenshot {

/**
 *  Takes screenshot and saves the image
 * 
 * @param {string} format. Format can take the value of either 'jpg' or 'png'
 * On ios, only 'jpg' format is supported
 * @param {number} quality. Determines the quality of the screenshot. 
 *        Default quality is set to 100.
 * @param {string} filename. Name of the file as stored on the storage 
 */
  @Cordova({
    successIndex: 1,
    errorIndex: 0
  })
  static save (format: string, quality: number = 100, filename: string) : Promise<any> {return}

/**
 *  Takes screenshot and returns the image as an URI
 * 
 * @param {number} quality. Determines the quality of the screenshot. 
 *        Default quality is set to 100.
 */

  @Cordova({
    successIndex: 1,
    errorIndex: 0
  })
  static URI (quality: number = 100)  : Promise<any> {return}
}
```

**Comment by ihadeed** [comment]
@panuganti 

To answer your questions:
- You must fork the repository, then pull your fork into your local machine. Follow this guide for more information on forking repos: https://help.github.com/articles/fork-a-repo/

- I haven't used the demo personally and I don't think it has been updated. You can create a blank Cordova/Ionic app and test `ionic-native` there.

---

As for the code you have written, it looks good to me and that should work. Just a few notes:
- Why is there a default value for the `quality` params?
- No need to import `CordovaProperty` since we aren't wrapping any properties
- No need to `declare var window;` since we aren't calling `window` in this plugin

Other than that it looks good! Send a PR once you've figured out the Github issues and I will merge it.
