### ISSUE TITLE
@ionic-native/speech-recognition doesn't work in ionic3

### ISSUE THREAD

**Issue by choatehall** [driftyco/ionic-native#1378]
I followed this video https://www.youtube.com/watch?v=dPbT_kElSXA and implemented in ionic3, but I got a blank page on my iPhone

**Comment by monichols** [comment]
Did you ionic serve --l before running on device? that should tell you what the problem is. 

Also, make sure to add SpeechRecognition to your app module like this::


import { SpeechRecognition, SpeechRecognitionListeningOptionsAndroid, SpeechRecognitionListeningOptionsIOS } from '@ionic-native/speech-recognition';


  providers: [
    SpeechRecognition, ;
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]

**Comment by danielsogl** [comment]
Hey @choatehall,

can you post your package.json and your code where you imported/used the plugin?
