### ISSUE TITLE
Cannot find module "ionic-native"

### ISSUE THREAD

**Issue by autotranzmoreshwar** [driftyco/ionic-native#1403]
my ionic info
![ionicinfo](https://cloud.githubusercontent.com/assets/27890822/25304571/8c779d12-2787-11e7-9d4b-14a9f9dba041.PNG)

solution please
![hello](https://cloud.githubusercontent.com/assets/27890822/25304564/75d5e758-2787-11e7-902c-c0ae67f928b0.PNG)

**Comment by niojihy** [comment]
This issue is associated with the old import 'ionic-native'

in my case :
import { StatusBar, Splashscreen } from 'ionic-native';
I removed and added the new :

https://ionicframework.com/docs/native/status-bar
https://ionicframework.com/docs/native/splash-screen

_If this is also your case, do not forget to add also in the module provider_

**Comment by danielsogl** [comment]
Hey@autotranzmoreshwar,
can you close this issue? 
You tried to access the old Ionic Native 2.x plugin.
