### ISSUE TITLE
Media plugin: List of bug I found so far.

### ISSUE THREAD

**Issue by baksagimm** [driftyco/ionic-native#1407]
1. Media Plugin 3.5.0 doesn't fire promise. The bug emerged again. So I have no control over the MediaObject and onStatusUpdate stays undefined.

2. Luckily, Media Plugin 3.4.4 do fire the promise. But it doesn't seem to retrieve file's play position and duration data no matter how long I wait. Both file:MediaObject properties and via getCurrentPosition() or getDuration() don't give the info of the file.

3. Since MediaObject doesn't give me the duration/position data, the seekTo() Does not work either.

**Comment by rapropos** [comment]
> Media Plugin 3.5.0 doesn't fire promise.

Can you see if this is still a problem with 3.6.0?

**Comment by baksagimm** [comment]
@rapropos Nope. It don't seem to call onSuccess.

**Comment by baksagimm** [comment]
@rapropos Nope. It seems this time, media.create returns undefined.

**Comment by danielehrhardt** [comment]
yes same here

**Comment by AleFons** [comment]
According to my testing, getDuration() seems to only work after the file has finished playing at least once; it also sometimes simply won't work and I'm not sure what causes it.

**Comment by ghenry22** [comment]
ionic-native 3.8.0 resolves the callback issue.  All callbacks are now properly implemented and docs are up to date with correct examples that match the implementation.

Seek and getcurrentposition work perfectly for me.  I don't use duration because I get that from the server side already.

I do know that there are some quirks with duration, Android for example will almost always return duration 0 for sources from http but from local file it's fine. This effectively means that you often cannot seek while streaming an audio file on Android.  iOS does not have this issue.  Seems to be very dependant on the source as well, some files work, some don't for me, probably something to do with the encoding.

**Comment by ihadeed** [comment]
Looks like any Ionic Native issues related have been fixed, closing this issue. 

Feel free to submit a PR to clarify any quirks you find with the plugin.
