### ISSUE TITLE
SocialSharing Plugin: Delay/Latency of ~ 2-4 secs or more

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic-native#143]
I've observed a lag of ~2-4 secs from the time a call to SocialSharing plugin is made to the time the social sharing options screen on my phone. This makes it feel not responsive for a short while.

**Comment by ihadeed** [comment]
Did you try to use the plugin without the Ionic Native wrapper? (using the original plugin API)

Also what platform(s) did you test this on?

Thanks.

**Comment by panuganti** [comment]
1) No. I did not use original plugin API.
2) This is on Android 6.0 (LG G3)

**Comment by ihadeed** [comment]
@panuganti can you try and use the original plugin API and compare the speeds?

I'm trying to figure out if the delay is caused by Ionic Native or the plugin itself.

**Comment by panuganti** [comment]
Sorry, I don't know how to use the native plugin without ionic

**Comment by ihadeed** [comment]
No problem @panuganti I will test it when I get a chance.
Thank you for your patience.

**Comment by ihadeed** [comment]
Hey @panuganti it seems like the speed is the same whether I'm using the Ionic-native wrapper or the original plugin functions. 

This might be an issue caused by the device or the plugin itself. Ionic native isn't slowing things down that much.

I recommend that you test your application on different devices (see [AWS Device Farm](https://aws.amazon.com/device-farm/)) and/or [open an issue with the original developer](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/new) if necessary.

**Comment by panuganti** [comment]
Ok. Thanks for the update

**Comment by FdezRomero** [comment]
@panuganti This is long known issue with the plugin, I have also been experiencing it without Ionic Native in an Ionic v1 app.
