### ISSUE TITLE
Calendar: returns OK even if no event was made

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#152]
When using the calendar plugin the promise seems to resolve with just the string "OK". It would be awesome if it could return if the event was created or not. So for example on android, if the user starts to create the event (using `createEventInteractively()`) but then backs out of Google Calendar it would be nice if the promise resolved with `event not created` or something of the like.

**Comment by ihadeed** [comment]
Hey @jgw96 

It looks like this issue is caused by the plugin itself and not Ionic Native. We are just wrapping the function and linking the success/error callbacks to the returned promise. 

I suggest you open an issue with @EddyVerbruggen to get that feature implemented. 

https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin
