### ISSUE TITLE
Calendar: Requesting permission

### ISSUE THREAD

**Issue by maxx0r** [driftyco/ionic-native#156]
Currently there's no implementation for requesting permissions in the calendar plugin. Could you port that?

My app is placing multiple items in the calendar so that's triggering a shitload of permission requests :)

**Comment by ihadeed** [comment]
Thanks for pointing it out. 

Just to verify that I'm addressing the same issue, you are using Android 6 device, is that correct?
I noticed these new methods implemented by the plugin developer: 
https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin#android-6-m-permissions

If adding them fixes your issue, then the fix should be available in the next release. Otherwise, please let me know so I can investigate this further.
