### ISSUE TITLE
Should I worry about plugins using the main thread?

### ISSUE THREAD

**Issue by onkelfredrik** [driftyco/ionic-native#187]
i'm getting the following output from Xcode:
````THREAD WARNING: ['StatusBar'] took '84.100098' ms. Plugin should use a background thread.```

**Comment by ghenry22** [comment]
That's something that would need to be changed in the cordova plugin itself.  It is not caused by or related to using ionic-native.  Unless there is a good reason for a request to be synchronous then background threading in the native code of the plugin is probably a good idea and you could raise an issue against the cordova statusbar plugin for it and see what they say.
