### ISSUE TITLE
[Q&A] Do ionic-native support websql fallback in dev env?

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic-native#263]
The previous way of using the `SqlStorage` worked with websql as fallback in the browser (basically when in development).

```js
import {Storage, SqlStorage} from 'ionic-angular';
export class DB {
  public db: any = new Storage(SqlStorage, {name: 'sonoramobile'});
}
```

Does `ionic-native` supports websql as a fallback where Sqlite can't be used?

**Comment by danbucholtz** [comment]
Yes.  It should just work.  Let me know if you have any issues.

Thanks,
Dan

**Comment by ihadeed** [comment]
Hey @Luchillo 

You're using `SqlStorage` from `ionic-angular` package. That is part of Ionic Framework 2.0. (AFAIK)

This repo is for the Native section only. http://ionicframework.com/docs/v2/native/

There is (SQLite)[http://ionicframework.com/docs/v2/native/sqlite/] plugin that is a part of ionic-native, which you can use instead of `SqlStorage` if you would like ... Not sure which one is a better wrapper.

**Comment by Luchillo** [comment]
I do know this is the native repo, i was looking to see if i would be better transitioning from `SqlStorage` to `ionic-native` sqlite solution, however i have been digging in the code and i see nothing about handling both sqlite and websql cases, specifically the open database function:
[sqlite.ts#L69-L80](https://github.com/driftyco/ionic-native/blob/master/src/plugins/sqlite.ts#L69-L80)

**Comment by ihadeed** [comment]
Well the code here is just a wrapper. The original plugin would have to
provide that fallback feature.

**Comment by Luchillo** [comment]
Well i've scanned the docs for the plugin soo, so far it seems i have to stick with `SqlStorage`.
