### ISSUE TITLE
(Request)Return observables from all plugins

### ISSUE THREAD

**Issue by sfabriece** [driftyco/ionic-native#321]
I see that some wrappers return promises and others Observables. It would be desirable to have the api return both types.

Any thoughts?

**Comment by ihadeed** [comment]
We return a promise when the plugin method takes callbacks as parameters. And we return an observable when we are wrapping an event listener.

I don't see why would we provide both observables and promises for all functions. Can you provide a use case?

**Comment by sfabriece** [comment]
It's purely for consistency. 

Because observables are chainable and ionic2 uses them, it would nice to not have to call `Observable.fromPromise` every time I need to use plug-ins. I could just assume that the chain would work.

**Comment by ihadeed** [comment]
I personally don't see the benefit of this but I will leave this open for the ionic team to give you an answer. 

@mhartington @mlynch

**Comment by mhartington** [comment]
I personally don't see the benefit. While it may not be consistent, I think it does provide a clear separation between methods that return once and methods/events that get fired multiple times.

Perfect example, the bluetooth plugin.`scan` is a perfect use case for an observable because it gets called multiple times and returns different values each time.

But something like the camera plugin doesn't fit this. You call `getPicture`, take a photo, and return the data from that single instance. You're not returning multiple photos, just a single one. In this case, `getPicture().then` seems more a better fit.

**Comment by mlynch** [comment]
Let's keep this open to review over time, I don't think we need to make any changes currently
