### ISSUE TITLE
Observable Usage with Angular 1.x?

### ISSUE THREAD

**Issue by MattHoneycutt** [driftyco/ionic-native#348]
Do observables (such as the return of Geolocation.watchPosition()) work with Angular 1.x's digest loop?  Or do I manually need to fire a $scope.$digest() in my subscribe callback?

I've got this subscription:

```jscript
            subscription = $cordovaGeolocation.watchPosition().subscribe(data => {
                vm.latitude = data.coords.latitude;
                vm.longitude = data.coords.longitude;
                console.log(data, vm);
            });
```

I can see the data being assigned, but it never refreshes the view, because a digest loop is never started.

**Comment by MattHoneycutt** [comment]
Actually, it looks like this question would apply to promises as well.  Do I need to manually call $scope.$digest or $scope.$apply?  Should something else be calling them?  Or is there another elegant solution to this problem for Angular 1.x that I'm overlooking?

**Comment by ihadeed** [comment]
For promises, you can just use them directly without having to modify anything. 

Before wrapping any method call, Ionic Native attempts to find ES6 Promise support, if that's not found, it will attempt to find `window.angular` (if found, will use $q), and if that's not found either it will throw a `console.warn` to let you know that you need to add a polyfill for promise support.

As for observables, I haven't done any experiments with that yet but I guess that it should work out of the box since the files `ionic.native.js` and `ionic.native.min.js` are produced by a browserify command that should pull all the required code from `rxjs` package.

I will close this for now, but do reopen or comment if you have further questions or difficulties.

**Comment by MattHoneycutt** [comment]
That doesn't seem to be the case.  I'm using ionic-native 1.3.9 with Angular 1.5.7.  Here's my code using the $cordovaGeolocation plugin:

```jscript
                $cordovaGeolocation.getCurrentPosition().then(data => {
                    console.log('Initial get completed.', data);
                    vm.latitude = data.coords.latitude.toFixed(4);
                    vm.longitude = data.coords.longitude.toFixed(4);
                });
```
My console.log is executed, but my view never updates, because a digest is never triggered.  

If I wrap the call in $scope.$apply, the view updates as expected:

```jscript
            $cordovaGeolocation.getCurrentPosition().then(data => {
                $scope.$apply(() => {
                    console.log('Initial get completed.', data);
                    vm.latitude = data.coords.latitude.toFixed(4);
                    vm.longitude = data.coords.longitude.toFixed(4);
                });
            });
```

Am I doing something wrong?

**Comment by mlynch** [comment]
I just updated the readme with a note about ng1 and observables for now

**Comment by MattHoneycutt** [comment]
So this should work for promises now, but observables will still need a $scope.$apply wrapper, correct?

**Comment by mlynch** [comment]
Correct, and with the merged $q fix the promises won't require the apply.
