### ISSUE TITLE
[Req] Change private to protected in SqLite adapter

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic-native#350]
I'm extending the SqLite adapter in order to support WebSql in development, however it seems the `_objectInstance` variable is privated and thus i can't reach it from my customSQLite provider, here's what i'm doing:

```ts
import { Injectable } from '@angular/core';
import { SQLite } from 'ionic-native';

declare var sqlitePlugin;
declare var openDatabase;

@Injectable()
export class CustomSQLite extends SQLite {
  openDatabase(config: any): Promise<any> {
    return new Promise((resolve, reject) => {
      if (sqlitePlugin) {
        sqlitePlugin.openDatabase(config, db => {
          this._objectInstance = db;
          resolve(db);
        }, error => {
          console.warn(error);
          reject(error);
        });
      } else {
        this._objectInstance = openDatabase(config.name, '1.0', 'database', 5 * 1024 * 1024);
        resolve(this._objectInstance);
      }
    });
  }
}
```

As it's a private var it doesn't allow me to change that variable, thus i would like that variable to change from `private` to `protected`, the compiler keeps yelling about that error and ionic won't compile, please can you make that change or is there a way to tell `ts` to not check that var?

**Comment by mhartington** [comment]
Since this is for ionic-native, web-sql is not the intended use case.  Instead, using the ionic SqlStorage class instead is a better option

http://ionicframework.com/docs/v2/api/platform/storage/SqlStorage/

It will auto check if you have the sqlite plugin installed and use that, and if not, it will use websql, so it will work in the environments you need.
