### ISSUE TITLE
Don't require observable subscribe to run

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-native#408]
Right now some operations (might be all observables) only run (like `Toast.show`) after a subscription has been created on the observable, forcing the caller to set up a listener. This should be fixed to run regardless of subscription

**Comment by tkem** [comment]
Well, isn't this how observables are _supposed_ to work? Like Angular 2 `Http`, for example? You can always turn this into a "hot" observable using `publish`/`connect`...

**Comment by mlynch** [comment]
@tkem yea I think you're right. Perhaps this is a case where observable is just the wrong return type for Toast

**Comment by tkem** [comment]
Probably, though I guess in this case an Observable was used because the `Toast.show()` success handler might be called multiple times if the toast is tapped: https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin#receiving-a-callback-when-a-toast-is-tapped
Whether this is good interface design in the first place is debatable, of course.

**Comment by tkem** [comment]
I tried out native Toast myself for the first time right now, and besides having to subscribe for the Toast to be shown, I think (please correct me if I'm wrong) I also have to unsubscribe *manually* to prevent resource leaks.
I would have assumed the observable to complete automatically when the Toast disappears, but this does not seem to be the case.
However, as soon as I unsubscribe the toast gets hidden (`clearFunction: 'hide'`), so the best thing I could come up with quickly is something like
```
Toast.show(message, duration.toString(), position).timeout(duration).subscribe(
  result => console.log('Toast shown or clicked', result),
  error => console.log('Toast error or timeout', error),
  () => console.log('Toast complete (never gets called)')
);
```
so the observable times out automatically after the same duration as set for the toast.

I'd really like to hear that I'm completely wrong here...

**Comment by ihadeed** [comment]
@mlynch so do you think we should just use promises because it makes more sense and eliminate the feature to notify the user when the toast is tapped? 

Not sure how that feature is beneficial anyways.

**Comment by keithdmoore** [comment]
How about '.first().subscribe()' ?

**Comment by rob3c** [comment]
`.first().subscribe()` or `.take(1).subscribe()` would work, but you can always do `.toPromise()` on the Observable to get a single value and not worry about unsubscribing, since it auto-unsubscribe afterwards.

I agree the tapping feature doesn't seem useful except maybe to dismiss it early, although tapping an actual button on a toast can be handy.

The overloading of the show and click events in the same observable is a bit confusing since they're semantically different. The first `next` event is `onShow`,  the second `next` is `onClick` (tedious to track), and `complete` is essentially `onClick` too, since it won't complete otherwise (handy to avoid counting `next`s, though.) A more common use of observables is as a stream of similar types of things. Using them with state machines is ok when you're passing the next state explicitly, but here it's implicit and a bit awkward.

More importantly, having the equivalent of a `finally` action when you don't care about clicks leads to unnecessary code duplication. Since you can't just `.finally()` on the observable, you have to duplicate `finally` actions across your `next` and `error` handlers. However, this could be remedied by completing the observable after it's no longer visible/clickable (at the expense of tracking `next` counts if you were using `complete` for `onClick`). Of course, you can `.timeout()` the observable yourself, but that triggers `error` for a timeout.

One argument for keeping it as an observable is similar to angular2's Http, which returns an observable for a single value where you might expect a promise: `unsubscribe` lets you cancel the request (hide the toast, in this case, though not sure if it really does this), whereas promises have no inherent cancellation mechanism.
