### ISSUE TITLE
Make NativeStorage implement IStorageEngine

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic-native#507]
In addition to the functions directly provided by `cordova-plugin-nativestorage`, it would be nice to also have NativeStorage implement `IStorageEngine` so it can be used as an injected `Storage`, similar to Ionic's `LocalStorage` and `SqlStorage`. For example:
```
import { Storage } from 'ionic-angular';
import { NativeStorage } from 'ionic-native';

// Here we could replace it with LocalStorage or SqlStorage without changing the rest of the code
let storage = new Storage(NativeStorage);

storage.set('key', 'value');
// ...
storage.get('key').then((value) => {
  console.log(value);
}).catch((error) => {
  console.error(error);
});
```

**Comment by ihadeed** [comment]
This would be something to discuss over at the Ionic Framework repo since this would be a framework feature, not an Ionic Native feature.

**Comment by imgx64** [comment]
This feature already exists in Ionic 2 (`Storage`, `StorageEngine`, `IStorageEngine`), and it's already implemented by `SqlStorage` and `LocalStorage` (see [here](https://github.com/driftyco/ionic/tree/master/src/platform/storage)).

What I'm asking for is to simply implement it in `NativeStorage`, which is part of Ionic Native.

**Comment by ihadeed** [comment]
I understand what you're asking for.

Ionic Native provides a wrapper for Cordova plugins. The wrapper emulates
the original plugins' APIs.

In order to make the Native Storage (or other type of storage) compatible
with the Ionic Framework's Storage Engine, we need to write another wrapper
that extends the StorageEngine class. This is something that can not be
part of  Ionic Native, it should be part of the Ionic Framework.

I'm not saying this idea is being rejected, I'm actually with you on it.
I'm just saying this is not the right place to discuss it.

I recommend that you open an issue at the Ionic repository (where the
StorageEngine class is).

**Comment by imgx64** [comment]
I see. I looked at the code and realized that ionic-native is a metadata-driven wrapper (using `@Plugin`, etc). I was mistakenly thinking the wrappers were manually written and that they could be modified freely.

I filed an Ionic issue [here](https://github.com/driftyco/ionic/issues/7935).
