### ISSUE TITLE
TODO: Themeable In App Browser

### ISSUE THREAD

**Issue by prantikv** [driftyco/ionic-native#549]
I recently found myself using the "Themeable In App Browser"

here is the [github link](https://github.com/initialxy/cordova-plugin-themeablebrowser)

The plugin adds a lot of features over the inappbrowers plugin. The best one is the ablity to customize the browser header bar which provides consistent UI.

Would love to see that added to the Ionic-native code base.

ISSUES: 
The themeablebrowser plugin does not support the loadstart and loadstop events of the original inappbrowser [here](https://www.npmjs.com/package/cordova-plugin-inappbrowser#inappbrowseraddeventlistener).

**Comment by ihadeed** [comment]
Great plugin, we will add it soon.

**Comment by Sampath-Lokuge** [comment]
Hi @ihadeed 

Can you please tell me how to use it? I have a huge problem now with the latest in app browser plugin.
You can see the issue here.Hope I can resolve that issue if I use above plugin.Hence it has a back button to the app.Please help me for this.Thanks.

[**Stackoverflow**](http://stackoverflow.com/questions/43069812/how-to-get-back-to-the-app-after-in-app-browser-view) 

[**Video about this issue**](https://youtu.be/B2s0tnNRWuU)

**Comment by ihadeed** [comment]
@Sampath-Lokuge see http://ionicframework.com/docs/v2/native/themeable-browser/

**Comment by Sampath-Lokuge** [comment]
Hi @ihadeed 

Oh.. Thanks a lot.I'll try that.One question, Can you please tell me what do you think about the issue which I have mentioned on above URL? How can I resolve that issue? I'm trying to find a solution for that whole day.But no luck yet.Do you have any workaround at least? Thank you.

**Comment by balachappidi9** [comment]
Hi @ihadeed

Can we pass parameters in this? 
The parameter are having a url, key and value in it.
