### ISSUE TITLE
Broken - SMS and CallNumber plugin

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic-native#643]
```
ionic plugin add cordova-sms-plugin
ionic plugin add call-number
```

These two plugins have different name when installed.

```
com.cordova.plugins.sms
mx.ferreyra.callnumber
```

so when I do `ionic state save`, it saves `com.cordova.plugins.sms` `mx.ferreyra.callnumber` in my package.json which breaks when I do `ionic state restore`

```
cordova plugin add com.cordova.plugins.sms
Caught exception:
 undefined 

```

@ihadeed IMHO, you should rename these plugins to use original name to avoid conflicts.

**Comment by ihadeed** [comment]
Hey

This is an issue caused by the plugin vendors, the information they have stored in config.xml does not match their npm package names. It's not something we can control on our end, I suggest you get in touch with them to fix the issue.

What I do in this situation is edit my package.json manually and modify the `id` value to the correct npm package name to avoid these problems when running `ionic state restore/reset`

**Comment by aggarwalankush** [comment]
@ihadeed Please see https://github.com/cordova-sms/cordova-sms-plugin/issues/103#issuecomment-253403364. Owner of cordova sms plugin updated plugin name. Would you please update the ionic-native and docs to reflect the changes?

**Comment by ihadeed** [comment]
@aggarwalankush our docs don't need to be updated. 

The developer changed the cordova plugin ID, not the package name. Which solves the problem that you've mentioned earlier.
