### ISSUE TITLE
How to properly use ionic-native?

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic-native#66]
Hey,

I'm developing an Ionic 2 app and I'm struggling with ionic-native. Do I have to add the plugins on the CLI manually and call them with ionic-native or this is done automatically when downloading ionic-native?

When I try to use ionic-native without adding the plugin, I get an undefined when trying to access it. When I add the plugin, it won`t build. 

Any docs that could assist me?

**Comment by ihadeed** [comment]
Hey @Artfloriani ,

As of now, you have to add the plugins using the CLI manually in order to successfully call their Ionic Native methods. 

Assuming you've installed the ionic-native npm package, follow these three steps to use any plugin:

**1. Install the plugin using CLI**
Every plugin has the install command at the top of their docs page. Some might not be available as of now in the docs since they haven't been updated yet, but you can find most recent changes on the staging site here: http://ionic-site-staging.herokuapp.com/docs/v2/native/Flashlight/

So for example we will be working with the Flashlight plugin. Run this commnd to install the plugin first:
```shell
cordova plugin add cordova-plugin-flashlight
```

**2. Import the plugin from `ionic-native`**
```js
import {Flashlight} from 'ionic-native'
```

**3. Call the method you need**
```js
Flashlight.toggle();
```

Hope that helped.

**Comment by Artfloriani** [comment]
Thank you @ihadeed.

As the Geolocation plugin works without installing it, I thought others would be just the same.

I followed your steps for the [ImagePicker](http://ionic-site-staging.herokuapp.com/docs/v2/native/Image%20Picker/) plugin but I still get 'undefined' when trying to access the ImagePicker. When I try to add the LocalNotification plugin it won't even build. I guess both of these issues have nothing to do with ionic-native, I'll try to debug it further.

Thank you.

**Comment by Artfloriani** [comment]
I found a fix for all the issues. Thank you @ihadeed :)

**Comment by ihadeed** [comment]
@Artfloriani from my experience the GeoLocation plugin doesn't work on all Android devices without installing the plugin. Works on the browser fine. Not sure about iOS.

Local notification and image picker haven't been tested yet.

I'm glad you found solutions to your problems.
