### ISSUE TITLE
Device 

### ISSUE THREAD

**Issue by Vanclief** [driftyco/ionic-native#954]
Im aware of the changes stated in 2.11.11 where Device.device.uuid becomes Device.uuid. 

> **BREAKING CHANGES**
> 
> device: device property no longer exists
> For example, `Device.device.platform` becomes `Device.platform now.`
> 
> https://github.com/driftyco/ionic-native/releases

**Problem description:** When calling Device.uuid in the browser, instead of getting return undefined, I get an empty object. This happens since 2.11.11

**Procedure:** `Console.log(Device.uuid);`
**Expected Outcome:** `Undefined`
**Experienced Outcome:** `{}`

**Comment by ihadeed** [comment]
That's happening because you're running on `ionic serve` and the cordova platform isn't available there. Ionic Native returns `{}` when a property doesn't exist (when cordova isn't available). See https://github.com/driftyco/ionic-native/blob/master/src/plugins/plugin.ts#L433.

I should probably change that and make it return `null` and throw a console warning.

**Comment by Vanclief** [comment]
@ihadeed Yes I understand. I used to have a method to check if cordova wasn't available, that used to work perfectly before this change. I think it would be great to make it return an `null` as you say, easier to check for.

Thanks for the quick reply.
