### ISSUE TITLE
Device API documentation inconsistencies

### ISSUE THREAD

**Issue by tycho01** [driftyco/ionic-native#962]
I'm trying to use the Device API, and am feeling somewhat confused. The [docs](http://ionicframework.com/docs/v2/native/device/) demonstrate a `Device.uuid` as a string, then below document it as a method, while the TS typings appear to be of the opinion all there is you could access is `Device.device.uid`. These consistencies feel very confusing, not having actually tried which claims are real yet.

**Comment by ramonsan** [comment]
Device.device.uuid is the old way to get it. Since [2.2.11](https://github.com/driftyco/ionic-native/releases/tag/v2.2.11), device is removed and all properties are moved just to Device.

The method listed below is referent to public getter of uuid in Device class, you can see it in [source code](https://github.com/apache/cordova-plugin-device/blob/master/src/android/Device.java#L111-L114).

So, the correct way to get uuid from 2.2.11+  is **Device.uuid**.

**Comment by tycho01** [comment]
Thanks, that explains the inconsistency with TS. In that case we should be good if we update the doc example to add `()`.

**Comment by ihadeed** [comment]
@tycho01 we'll work on removing the `()` from properties.
