### ISSUE TITLE
NativeStorage.getItem raises error in browser on windows

### ISSUE THREAD

**Issue by ivanovvitaly** [driftyco/ionic-native#967]
Getting error when trying to use NativeStorage.getItem in browser on windows machine, however works fine in browser on mac os.

error from console 

```
window.angular.element is not a function
    at getPromise (plugin.js:139)
    at wrapPromise (plugin.js:158)
    at Function.<anonymous> (plugin.js:325)
    at Function.value [as getItem] (plugin.js:386)
```

Please advice

 
cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v7.2.1
Xcode version: Not installed

**Comment by ihadeed** [comment]
To use the plugin on the browser you need to run `ionic run browser`. It won't work on `ionic serve`.

**Comment by ihadeed** [comment]
You're getting this error because for some reason `window.angular` is defined. That variable shouldn't be defined in `Ionic 2` AFAIK. 

Are you using the ng-upgrade (not sure of the name) module? Can you reproduce this same issue with a fresh project?

If this is a real issue then I can modify `plugin.ts` to check that `window.angular.element` exists and not just `window.angular`.

**Comment by ivanovvitaly** [comment]
Seems like caused by browser cache. Created new project, cleared browser cache, got nice cordova_not_available error from getItem promise.
